services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-nestjs}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-nestjs}
      POSTGRES_DB: ${DB_NAME:-nestjs_tutorial}
    ports:
      - '${DB_PORT:-5433}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'

volumes:
  postgres_data:
